WikisCommunity/home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('', views.index),
    path('policy/', views.policy, name='policy'),
    path('login/', auth_views.LoginView.as_view(template_name='pages/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('register/', views.register, name='register'),
    path('account/', views.edit, name='account'),
    path('page_request/', views.page_request, name='page_request'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
                    template_name='account/password_change_form.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
                    template_name='account/password_change_done.html'), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
                    template_name='account/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
                    template_name='account/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                    template_name='account/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
                    template_name='account/password_reset_complete.html'), name='password_reset_complete'),
]

WikisCommunity/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    path('page/', include('wikipage.urls', namespace='wikipage')),
    path('article/', include('wikiarticle.urls', namespace='wikiarticle')),

    path('', include('home.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WikisCommunity/wikipage/urls.py
from django.urls import path
from . import views


app_name = 'wikipage'


urlpatterns = [
    path('', views.page_list, name='page_list'),
    path('search/', views.page_search, name='page_search'),
    path('<slug:wiki_category_slug>/', views.page_list, name='page_list_by_category'),
    path('<int:id>/<slug:page_slug>/', views.page_index, name='page_index'),
    path('<int:id>/<slug:page_slug>/<slug:page_category_slug>', views.page_index, name='article_list'),

    path('<slug:page_slug>/edit/', views.page_edit, name='page_edit'),
    path('<slug:page_slug>/add_category/', views.page_add_category, name='page_add_category')
]

WikisCommunity/wikipage/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.template.defaultfilters import slugify


STATUS_CHOICES = (
    ('1','NORMAL'),
    ('2', 'RESTRICT'),
    ('3','LOCK'),
)


class WikiCategory(models.Model):
	title = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, verbose_name="URL", unique=True)
	#description = models.CharField(max_length=255)

	class Meta:
		ordering = ('title',)
		verbose_name = 'Category'
		verbose_name_plural = 'Categories'

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('wikipage:page_list_by_category', args=[self.slug])

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.title)
		return  super().save(*args,**kwargs)





class WikiPage(models.Model):
	wiki_category = models.ForeignKey(WikiCategory, 
						related_name='wiki_pages', on_delete=models.CASCADE)
	title = models.CharField(max_length=100, db_index=True)
	slug = models.SlugField(max_length=200, verbose_name="URL", db_index=True)
	created = models.DateTimeField(default=timezone.now)

	class Meta:
		ordering = ('title',)
		index_together = (('id', 'slug'),)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('wikipage:page_index', args=[self.id, self.slug])

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.title)
		return  super().save(*args,**kwargs)
		
	def create_absolute_url(self):
		return reverse('wikiarticle:create_article', args=[self.id, self.slug])



class PageProperty(models.Model):
	page = models.OneToOneField(WikiPage, related_name='page_property', on_delete=models.CASCADE)
	logo = models.ImageField(blank=True, null=True, upload_to='pages/')
	slogan = models.CharField(max_length=100)
	about = models.TextField(blank=True, null=True)
	visibility = models.BooleanField(default=True)
	status = models.CharField(max_length=8, choices=STATUS_CHOICES, default='1')

	class Meta:
		verbose_name = 'PageProperty'
		verbose_name_plural = 'PageProperties'

	def __str__(self):
		return '{}'.format(self.page)

	@property
	def get_filter_category(self, id):
		return WikiCategory.objects.filter(id=id)


class PageStats(models.Model):
	page = models.OneToOneField(WikiPage, on_delete=models.CASCADE)
	edit = models.PositiveIntegerField(verbose_name="Edit times")
	view = models.PositiveIntegerField(verbose_name="View number")
	articles = models.PositiveIntegerField(verbose_name="Aricle number")

	class Meta:
		verbose_name = 'PageStats'
		verbose_name_plural = 'PageStats'

	def __str__(self):
		return '{}'.format(self.page)


class PageCategory(models.Model):
	title = models.CharField(max_length=100)
	slug = models.SlugField(max_length=200, verbose_name="URL", db_index=True)
	page = models.ForeignKey(WikiPage, 
					related_name='page_categories', on_delete=models.CASCADE)

	class Meta:
		ordering = ('title',)
		verbose_name = 'PageCategory'
		verbose_name_plural = 'PageCategories'

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('wikipage:article_list', args=[self.page.id, self.page.slug, self.slug])

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.title)
		return  super().save(*args,**kwargs)


"""class PageLog(models.Model):
	page = models.OneToOneField(Page, on_delete=models.CASCADE)
	time_stamp = models.DateTimeField(auto_now_add=True)
	content = models.TextField()
	editor = models.CharField(max_length=100) 
"""

WikisCommunity/wikipage/forms.py
from django import forms
from .models import PageProperty, PageCategory


class PageEditForm(forms.ModelForm):
    class Meta:
        model = PageProperty
        fields = ['logo', 'slogan', 'about', 'visibility', 'status']


class AddPageCategoryForm(forms.ModelForm):
	class Meta:
		model = PageCategory
		fields = ['title']


class SearchForm(forms.Form):
    query = forms.CharField(label='')

WikisCommunity/wikipage/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib import messages
#from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import WikiCategory, WikiPage, PageCategory, PageProperty
from .forms import SearchForm, PageEditForm, AddPageCategoryForm
from wikiarticle.models import Article, ArticleProperty
from home.decorators import checkgroup


def page_list(request, wiki_category_slug=None):
    wiki_category = None
    wiki_categories = WikiCategory.objects.all()
    object_list = WikiPage.objects.all() #filter(available=True)
    if wiki_category_slug:
        wiki_category = get_object_or_404(WikiCategory, slug=wiki_category_slug)
        object_list = WikiPage.objects.filter(wiki_category=wiki_category)
    paginator = Paginator(object_list, 9)
    page = request.GET.get('page')
    try:
        wiki_pages = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        wiki_pages = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        wiki_pages = paginator.page(paginator.num_pages)

    return render(request, 'wikipage/list.html', {'page': page, 
                                                'wiki_category': wiki_category, 
                                                'wiki_categories': wiki_categories, 
                                                'wiki_pages': wiki_pages})


def page_index(request, id, page_slug, page_category_slug=None):
    wiki_page = get_object_or_404(WikiPage, id=id, slug=page_slug)
    page_property = PageProperty.objects.get(page=wiki_page)
    page_category = None
    page_categories = PageCategory.objects.filter(page=wiki_page)
    object_list = Article.objects.filter(wiki_page=wiki_page, articleproperty__visibility=True)
    if page_category_slug:
        page_category = get_object_or_404(PageCategory, slug=page_category_slug)
        object_list = Article.objects.filter(page_category=page_category, articleproperty__visibility=True)

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)

    return render(request, 'wikipage/index.html', {'page': page, 
                                                'wiki_page': wiki_page, 
                                                'page_property': page_property, 
                                                'page_category': page_category, 
                                                'page_categories': page_categories, 
                                                'articles': articles})

@checkgroup('admin' or 'manager' or 'supporter' or 'page_owner' or 'page_manager')
def page_add_category(request, page_slug):
    wiki_page = get_object_or_404(WikiPage, slug=page_slug)
    page_property = PageProperty.objects.get(page=wiki_page)
    page_categories = PageCategory.objects.filter(page=wiki_page)
    if request.method == 'POST':
            form = AddPageCategoryForm(data=request.POST)
            if form.is_valid():
                new_page_category = form.save(commit=False)
                new_page_category.page = wiki_page
                new_page_category.save()
                return redirect('wikipage:page_index', id=wiki_page.id,
                                page_slug=wiki_page.slug)
    else:
            form = AddPageCategoryForm()

    return render(request, 'wikipage/add_category.html', {'add_category_form': form, 
                                                        'page_categories' : page_categories,
                                                        'page_property': page_property,
                                                        'wiki_page': wiki_page,
                                                        'page_slug': page_slug})


@checkgroup('admin' or 'manager' or 'supporter' or 'page_owner')
def page_edit(request, page_slug):
    wiki_page = get_object_or_404(WikiPage, slug=page_slug)
    page_property = PageProperty.objects.get(page=wiki_page)
    page_categories = PageCategory.objects.filter(page=wiki_page)
    if request.method == 'POST':
        edit_form = PageEditForm(request.POST, request.FILES, instance=page_property)
        if edit_form.is_valid():
            edit_page = edit_form.save(commit=False)
            edit_page.page = wiki_page
            edit_page.save()
            messages.success(request, 'Edit page property success.')
        else:
            messages.error(request, 'Invalid input.')

    else:
        edit_form = PageEditForm(instance=page_property)

    return render(request, 'wikipage/page_edit.html', {'edit_form': edit_form, 
                                                    'page_categories': page_categories,
                                                    'page_property': page_property,
                                                    'wiki_page': wiki_page,
                                                    'page_slug': page_slug})
    


def page_search(request):
    form = SearchForm()
    query = None
    object_list = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            object_list = WikiPage.objects.annotate(
                similarity=TrigramSimilarity('title', query),
            ).filter(similarity__gt=0.1).order_by('-similarity')


    paginator = Paginator(object_list, 9)
    page = request.GET.get('page')
    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        results = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        results = paginator.page(paginator.num_pages)

    return render(request, 'wikipage/search.html', {'page':page, 'form': form, 
                                                'query': query, 'results': results})

"""
    query = form.cleaned_data['query']

    search_vector = SearchVector('wiki_category', 'title')
    search_query = SearchQuery(query)
    queryset = WikiPage.objects

    results = queryset.annotate(rank=SearchRank(search_vector, search_query),
                    similarity=TrigramSimilarity('wiki_category', search_query) 
                    + TrigramSimilarity('title', search_query),
        ).filter(similarity__gt=0.1).order_by('-rank')
"""

WikisCommunity/wikipage/templates/wikipage/add_category.html
{% extends "base_page.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
  Add category | {{ wiki_page.title}} | 
{% endblock %}

{% block body %}
    <form action="." method="post" enctype="multipart/form-data" class="form-account">
        {% csrf_token %}
        {{add_category_form|crispy}}

        <div class="form-group row">
        	<div class="offset-4 col-8">
            	<br>
                <button name="submit" type="submit" class="btn btn-primary">Add new category</button>
            </div>
        </div>
    </form>
{% endblock %}

WikisCommunity/wikipage/templates/wikipage/index.html
{% extends "base_page.html" %}
{% load static %}

{% block stylesheet %}

<style>
.created {
  position: absolute;
  bottom: -16px;
  right: -18px;
  font-size: 18px;
}

.author_article {
  position: absolute;
  bottom: -17px;
  font-size: 18px;
  left: 21px;
}
</style>
{% endblock %}

{% block title %}
  {% if page_category %}{{ page_category.title }} | {% endif %} 
  {{ wiki_page.title}} | 
{% endblock %}

{% block body %}
    <div class="content_wiki" >
      {% if articles %}

       {% for article in articles %}
      <div class="card">
    <div class="row no-gutters">
        {% if article.header_image %}
        <div class="col-sm-5" style="background: #868e96;">
            <a href="{{ article.get_absolute_url }}">
                <img src="{{ article.header_image.url }}" class="card-img-top" alt="..." width="300px" height="350px"></a>
        </div>
        {% endif %}
        <div class="col-sm-7">
            <div class="card-body">
             <div class="card_title" style="margin-top: -23px;padding-bottom: 15px;">
                 <h4> {{ article.title }}</h4></div>
              <p><a href="{{ article.wiki_page.get_absolute_url }}"> {{ article.wiki_page.title }} </a> &gt;
                  <a href="{{ article.page_category.get_absolute_url }}"> {{  article.page_category.title }} </a> </p>
              <div class="row">

                <div class="author_article">
                  {{ article.is_author.username }}
                </div>
              <div class="created">
                {{ article.time_stamp|date:"Y-m-d" }}
              </div>
                </div>
            </div>
        </div>
    </div>
</div>
      {% endfor %}
         {% else %}
        <div class="card">
          <p>There are no Article yet.  </p>
        </div>
           {% endif %}
    </div>
{% endblock %}

WikisCommunity/wikipage/templates/wikipage/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
	{% if wiki_category %} {{ wiki_category.title }}
	{% else %} Pages List | 
	{% endif %}
{% endblock %}

{% block content %}
	<div class="container">

		<div class="row">
		    <div class="col-lg-3">
		    	<h1 class="my-4"></h1>
			    <div class="list-group">
						<a {% if not wiki_category %}
							class="list-group-item active"
						{% else %}
							class="list-group-item"
						{% endif %}
						 	href="{% url 'wikipage:page_list' %}" style="text-align:center"><b>All categories</b></a>

					{% for c in wiki_categories %}
						<a {% if wiki_category.id == c.id %}
							class="list-group-item active"
							{% else %}
							class="list-group-item"
						{% endif %}
						 	href="{{ c.get_absolute_url }}" style="text-align:center"><b>{{ c.title }}</b></a>
					{% endfor %}
					<br>
			    </div>
		    </div>
			<div class="col-lg-9">
				<div id="Indicator" class="carousel slide my-4" data-ride="carousel">
					
			    </div>
				<div class="row">
					{% for p in wiki_pages %}
						<div class="col-lg-4 col-md-6 mb-4">
							<div class="card h-100">
								{% comment %}
								<a href="{{ p.get_absolute_url }}">
									<img class="card-img-top" src="
									{% if p.image %}
										{{ p.page_property.logo.url }}
									{% else %}
										{% static 'image/no_image.png' %}
									{% endif %}">
								</a>
								{% endcomment %}
								<a href="{{ p.get_absolute_url }}">{{ p.title }}
								</a>
				            </div>
				       	</div>
					{% endfor %}
				</div>	
			</div>
			{% include "pagination.html" with page=wiki_pages %}
		</div>
	</div>
{% endblock %}

WikisCommunity/wikipage/templates/wikipage/page_edit.html
{% extends "base_page.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
  Edit Page Property | {{ wiki_page.title}} | 
{% endblock %}

{% block body %}
	<form action="." method="post" enctype="multipart/form-data" class="form-account">
		{% csrf_token %}
        {{edit_form|crispy}}
        <div class="form-group row">
        	<div class="offset-4 col-8">
            	<br>
                <button name="submit" type="submit" class="btn btn-primary">Update</button>
            </div>
        </div>
    </form>
{% endblock %}

WikisCommunity/wikipage/templates/wikipage/search.html
{% extends "base.html" %}
{% load static %}

{% block title %}Page Search | {% endblock %}



{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-lg-3">
			    <h1 class="my-4"></h1>
				<div class="list-group">
				    <form class="form-signin">
				    	<h5 class="form-signin-heading text-lg-center">Search<br> 
				    		{% if query %} "{{ query }}" {% endif %}
				    	</h5>
				    	<hr>
				    	<form action="." method="get">
				    		{% comment %}
							{{ form.as_p }}
							<input type="submit" class="btn btn-outline-dark" value="Search"> 
							<hr>
							{% endcomment %}
					    	{% with results.count as total_results %}
								Found {{ total_results }} result{{ total_results|pluralize }}
							{% endwith %}
						</form>
					</form>
					<br> 
				</div>
			</div>
			
			

			<div class="col-lg-9">
				<div id="Indicator" class="carousel slide my-4" data-ride="carousel"></div>
				<div class="row">
					{% for p in results %}
						<div class="col-lg-4 col-md-6 mb-4">
							<div class="card h-100">
								{% comment %}
								<a href="{{ p.get_absolute_url }}"> 
									<img class="card-img-top" src="
										{% if p.image %}
											{{ p.image.url }}
										{% else %}
											{% static 'image/no_image.png' %}
										{% endif %}	">
								</a>
								{% endcomment %}
								<div class="card-body">
									<h4 class="card-title">
										<a href="{{ p.get_absolute_url }}">{{ p.title }}</a>
									</h4>
								</div>
					       	</div>
						{% empty %}
							<p>*Can't found any result match your keyword.</p>
						{% endfor %}
					</div>	
				</div>
			</div>
		</div>
	{% if results %}
    	{% include "pagination.html" with page=results %}
  	{% endif %}
{% endblock %}