WikisCommunity/home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('', views.index),
    path('policy/', views.policy, name='policy'),
    path('login/', auth_views.LoginView.as_view(template_name='pages/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('register/', views.register, name='register'),
    path('account/', views.edit, name='account'),
    path('page_request/', views.page_request, name='page_request'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
                    template_name='account/password_change_form.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
                    template_name='account/password_change_done.html'), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
                    template_name='account/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
                    template_name='account/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                    template_name='account/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
                    template_name='account/password_reset_complete.html'), name='password_reset_complete'),
]

WikisCommunity/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    path('page/', include('wikipage.urls', namespace='wikipage')),
    path('article/', include('wikiarticle.urls', namespace='wikiarticle')),

    path('', include('home.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WikisCommunity/wikiarticle/urls.py
from django.urls import path
from . import views

app_name = 'wikiarticle'

urlpatterns = [
    path('create/<int:id>&<slug:page_slug>', views.create_article, name='create_article'),
    path('<slug:page_slug>/<slug:category_slug>/<slug:article_slug>', views.detail_article, name='detail_article'),
    path('edit/<slug:page_slug>/<slug:category_slug>/<slug:article_slug>', views.edit_article, name='edit_article'),
    path('search/', views.search_article, name='search_article'),
]

WikisCommunity/wikiarticle/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField
from wikipage.models import WikiPage
from django.contrib.auth.models import User
from  django.urls import reverse
from django.template.defaultfilters import slugify
from wikipage.models import PageCategory, WikiPage



STATUS_CHOICES = (
    ('1','NORMAL'),
    ('2', 'RESTRICT'),
    ('3','LOCK'),
)


class Article(models.Model):
	title = models.CharField(max_length=100)
	header_image = models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')
	content_article = RichTextUploadingField(blank=True, null=True)
	time_stamp = models.DateTimeField(default=timezone.now)
	slug = models.SlugField(null=True, unique=True)
	wiki_page = models.ForeignKey(WikiPage, related_name='Article', on_delete=models.CASCADE)
	is_author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
	page_category = models.ForeignKey(PageCategory, on_delete=models.CASCADE)

	class Meta:
		verbose_name = 'Articles'
		verbose_name_plural = 'Articles'
		ordering = ['-time_stamp']

	def __str__(self):
		return 'Article: {}'.format(self.title)

	def get_absolute_url(self):
		return reverse('wikiarticle:detail_article', args=[self.wiki_page.slug, self.page_category.slug, self.slug])

	def get_edit_absolute_url(self):
		return reverse('wikiarticle:edit_article', args=[self.wiki_page.slug, self.page_category.slug, self.slug])

	def save(self, *args, **kwargs):
		if not self.slug:
			super().save(*args, **kwargs)
			self.slug = '{}-{}'.format(slugify(self.title), self.id)
		return super().save(*args,**kwargs)


# Model show the attribute Article
class ArticleProperty(models.Model):
	article = models.OneToOneField(Article, on_delete=models.CASCADE, primary_key=True)
	visibility = models.BooleanField(default=True)
	status = models.CharField(max_length=8, choices=STATUS_CHOICES, default='1')

	class Meta:
		verbose_name = 'ArticleProperty'
		verbose_name_plural = 'ArticleProperties'

	def __str__(self):
		return 'ArticleProperty: {}'.format(self.article)


class ArticleStats(models.Model):
	article = models.OneToOneField(Article, on_delete=models.CASCADE)
	view = models.PositiveIntegerField(default=0)
	comment_number = models.PositiveIntegerField(default=0)

	class Meta:
		verbose_name = 'ArticleStats'
		verbose_name_plural = 'ArticleStats'

	def __str__(self):
		return 'ArticleStats: {}'.format(self.article)

class Comment(models.Model):
	article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
	content = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	is_user = models.ForeignKey(User, related_name='user_comment',on_delete=models.CASCADE, null=True)
	active = models.BooleanField(default=True)
	anonymous = models.CharField(blank=True, null=True, max_length=100)

	class Meta:
		ordering = ['created']

	def __str__(self):
		return 'ArticleComment: {}'.format(self.article)

WikisCommunity/wikiarticle/forms.py
from django.forms import ModelForm
from .models import Article, Comment,ArticleProperty
from django import forms


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'header_image', 'content_article', 'page_category' ]


class ArticlePropertyForm(ModelForm):
    class Meta:
        model = ArticleProperty
        fields = ['visibility', 'status']


class EditArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['content_article']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content', 'anonymous']


class SearchArticleForm(forms.Form):
        query = forms.CharField(label='')

WikisCommunity/wikiarticle/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .forms import ArticleForm, CommentForm, EditArticleForm, SearchArticleForm, ArticlePropertyForm
from .models import Article, ArticleProperty, ArticleStats
from django.views.generic import DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.search import TrigramSimilarity
from wikipage.models import WikiCategory, WikiPage, PageCategory
from django import template




@login_required
def create_article(request, id, page_slug):
    wiki_page = get_object_or_404(WikiPage, slug=page_slug)
    page_categories = PageCategory.objects.filter(page=wiki_page)
    if request.method == 'POST':
        form = ArticleForm(request.POST,request.FILES)
        if form.is_valid():
            new_article = form.save(commit=False)
            new_article.is_author = request.user
            new_article.wiki_page = wiki_page
            new_article.save()
            article_property = ArticleProperty.objects.create(article=new_article)
            article_stats = ArticleStats.objects.create(article=new_article)
            article_stats.save()
            article_property.save()

            return redirect('wikiarticle:detail_article', page_slug=new_article.wiki_page.slug,
                            category_slug=new_article.page_category.slug, article_slug=new_article.slug)
    else:
        form = ArticleForm(request.FILES)
    return render(request, 'wikiarticle/create.html',
                  {'form': form, 'wiki_page': wiki_page,
                   'page_categories': page_categories, })


def detail_article(request, page_slug, category_slug, article_slug):
    article = get_object_or_404(Article, slug=article_slug)
    status_article = int(article.articleproperty.status)
    # filter comments in article
    comments = article.comments.filter(active=True)
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.article = article
            if request.user.is_authenticated:
                new_comment.is_user = request.user
            article.articlestats.comment_number += 1
            new_comment.save()
    else:
        comment_form = CommentForm()
        article.articlestats.view += 1

    return render(request, 'wikiarticle/detail_article.html', {'article': article,
                                                                'comments': comments,
                                                                'comment_form': comment_form,
                                                               'status_article': status_article,})


def edit_article(request, page_slug, category_slug, article_slug):
    article = get_object_or_404(Article, slug=article_slug)
    status_article = int(article.articleproperty.status)
    property_form = None
    if request.user.is_superuser:
        property_article = get_object_or_404(ArticleProperty, article=article)
        if request.method == 'POST':
            form = EditArticleForm(request.POST, request.FILES, instance=article)
            property_form = ArticlePropertyForm(request.POST, instance=property_article)
            if form.is_valid() and property_form.is_valid():
                form.save()
                property_form.save()
                return redirect('wikiarticle:detail_article',
                                page_slug=page_slug,
                                category_slug=category_slug, article_slug=article_slug)
        else:
            property_form = ArticlePropertyForm(instance=property_article)
    else:
        if status_article == 1 or (status_article == 2 and request.user.is_authenticated):
            if request.method == 'POST':
                form = EditArticleForm(request.POST, request.FILES, instance=article)
                if form.is_valid():
                    form.save()
                    return redirect('wikiarticle:detail_article',
                                    page_slug=page_slug,
                                    category_slug=category_slug, article_slug=article_slug)
        else:
            return redirect('wikiarticle:detail_article',
                            page_slug=page_slug,
                            category_slug=category_slug, article_slug=article_slug)
    form = EditArticleForm(instance=article)
    return render(request, 'wikiarticle/edit.html', {'form': form, 'property_form': property_form, 'article': article })


def search_article(request):
    search_form = SearchArticleForm()
    query = None
    results = []
    if 'query' in request.GET:
        search_form = SearchArticleForm(request.GET)
        if search_form.is_valid():
            query = search_form.cleaned_data['query']
            results = Article.objects.annotate(
                similarity=TrigramSimilarity('title', query),).filter(similarity__gt=0.1).order_by('-similarity')
    return render(request, 'wikiarticle/search_article.html',
                  {'search_form': search_form, 'query': query, 'results': results})

WikisCommunity/wikiarticle/templates/wikiarticle/create.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Article {% endblock %}
<style>
    input {
    width: 100%;
    }
</style>
{% block content %}
<div class="left_wiki">
    <div class="card" style="background-color:#f1f1f1; border-style:none;">

    </div>
</div>
<div class="content_wiki">


<form action="{% url 'wikiarticle:create_article' id=wiki_page.id page_slug=wiki_page.slug %}"
      method="post" enctype="multipart/form-data" style="padding-top:40px;">
    {% csrf_token %}
    <div class="row" style="margin-left:2px;">
        <label for="id_page_category">Category:</label>
       <select name="page_category" required id="id_page_category">
        <option value="" selected="">---------</option>
           {% for category in page_categories %}
             <option value="{{ category.id }}" >{{ category.title }}</option>
           {% endfor %}
</select>
         <label for="id_title">Title:</label>
    <input type="text" name="title" maxlength="100" required="" id="id_title" style="width:50%">

    </div>
    <div class="row"  style="margin-bottom:10px;margin-left:2px;">
         <label for="id_header_image">Header image:</label>
        <input type="file" name="header_image" accept="image/*" id="id_header_image">
    </div>
        {{ form.content_article }}
        {{ form.media }}
    <input type="submit" value="Upload Article">

   </form>
    </div>
<div class="right_wiki">

</div>


{% endblock %}

WikisCommunity/wikiarticle/templates/wikiarticle/detail_article.html
{% extends 'base_page.html' %}
{% load static %}

{% block content %}
<div class="left_wiki">
    <div class="card" style="background-color:#f1f1f1;border-style:none;">

    </div>
</div>
<div class="content_wiki" >
        {% if article.header_image %}
    <div class="card">

       <img class="img_article"  src="{{ article.header_image.url }}"
			style="text-align:center;text-align:center;width: 100%;height: 450px;">

		   <h2 style="margin-top: 4px;"> {{ article.title }}</h2>
			<p><a href="{{ article.wiki_page.get_absolute_url }}"> {{ article.wiki_page.title }} </a> &gt;
                  <a href="{{ article.page_category.get_absolute_url }}"> {{  article.page_category.title }} </a> </p>
    {% endif %}

	</div>
	{% if status_article == 1 or  request.user.is_superuser or status_article == 2 and request.user.is_authenticated %}
   <a href="{{  article.get_edit_absolute_url  }}">Edit</a>
	{% elif status_article == 2 or status_article == 3 %}
	<p>The article is lock or restrict.So you cann't edit article</p>
	{% endif %}
    <div class="card">
         {{ article.content_article | safe }}
    </div>
    <div class="card" style="background-color:#edb9ee0d;">
        <h2>Comments</h2>
        <hr>
    <div class="be-comment-block">
        {% for comment in comments %}
	<h4 class="comments-title"> </h4>
	<div class="be-comment">
		<div class="be-img-comment">
			{% if comment.is_user.profile.photo %}
			<a href="blog-detail-2.html">
				<img src="{{ comment.is_user.profile.photo.url }}" alt="" class="be-ava-comment">
			</a>
			{% elif comment.is_user.is_superuser %}
				<img src="{% static 'images/admin.png' %}" alt="" class="be-ava-comment">
			{% else %}
				<img src="{% static 'images/undefined.png' %}" alt="" class="be-ava-comment">
			{% endif %}
		</div>
		<div class="be-comment-content">

				<span class="be-comment-name">
						{% if  comment.is_user.is_superuser %}
					<div style="color:red;">
						{{ comment.is_user.username }}
						</div>
					{% elif comment.is_user.is_authenticated %}
					<div>
						{{ comment.is_user.username }}
						</div>
						{% elif comment.anonymous %}
					<div>
						{{ comment.anonymous }}
					</div>
					{% else %}
					<div>
						anonymous
					</div>
						{% endif %}
					</span>
				<span class="be-comment-time" style="color:black">
					<i class="fa fa-clock-o" ></i>
					 {{ comment.created }}
				</span>

			<p class="be-comment-text">
				{{ comment.content }}
			</p>
		</div>
        {% empty %}
        <p>There are no comments yet.</p>
        {% endfor %}
	</div>

	<form class="form-block" action="{{ article_get_absolute_url }}"
          method="post" enctype="multipart/form-data">
        {% csrf_token %}
		<div class="row">
			{% if  not request.user.is_authenticated %}
			<div class="col-xs-12 col-sm-6">
				<div class="form-group">
					<input class="form-input"  name="anonymous" type="text" placeholder="Your name" >
				</div>
			</div>
			</div>
		<div class="row">
			{% endif %}
			<div class="col-xs-12 col-sm-6">
				<div class="form-group">
					<textarea class="form-input" name="content" required="" placeholder="Your text" style="width:566px;" ></textarea>
				</div>
			</div>
		</div>
		<input type="submit" class="btn btn-primary pull-right" value="Comment">
	</form>
</div>
</div>
</div>

{% endblock %}

WikisCommunity/wikiarticle/templates/wikiarticle/edit.html
{% extends 'base_page.html' %}

{% block title %} {{ article.title }} {% endblock %}

{% block content %}

<div class="left_wiki">
    <div class="card" style="background-color:#f1f1f1;border-style:none;">

    </div>
</div>

<div class="content_wiki" >
    <form action="{{ article.get_edit_absolute_url }}"
          method="post" enctype="multipart/form-data" style="width:100%; padding-top:70px" >
         {% csrf_token %}
        {% if property_form %}
            {{ property_form }}
        {% endif %}
        {{ form.content_article }}
        {{ form.media }}


        <input type="submit" value="Submit">
    </form>
</div>
{% endblock %}

WikisCommunity/wikiarticle/templates/wikiarticle/search_article.html
{% extends "base.html" %}
{% load static %}

{% block stylesheet %}

<style>
.created {
  position: absolute;
  bottom: -16px;
  right: -18px;
  font-size: 18px;
}

.author_article {
  position: absolute;
  bottom: -17px;
  font-size: 18px;
  left: 21px;
}
</style>
{% endblock %}

{% block menu %}
 <li>
      <form class="d-flex justify-content-center h-100"  method="get" action="{% url 'wikiarticle:search_article' %}">
        <div class="searchbar" style="padding:7px;">
          <input class="search_input" type="text" name="query" placeholder="Article search ..." style="height: 27px;">
          <input type="submit" class="search_icon" value="" style="
                 background: url('/static/images/icon_search.png');
                 background-size:cover;
                 margin-bottom: -9px;
                 background-color: aquamarine;
                 width: 25px;
                 height: 28px;
                 margin-left: -5px;
                 "> </div>
      </form>
    </li>
{% endblock %}

{% block content %}
<div class="left_wiki">
    <div class="card" style="background-color:#f1f1f1;border-style:none;">

    </div>
</div>
   <div class="content_wiki" >
      {% if results %}

       {% for article in results %}
      <div class="card">
    <div class="row no-gutters">
        {% if article.header_image %}
        <div class="col-sm-5" style="background: #868e96;">
            <a href="{{ article.get_absolute_url }}">
                <img src="{{ article.header_image.url }}" class="card-img-top" alt="..." width="300px" height="350px"></a>
        </div>
        {% endif %}
         <div class="col-sm-7">
            <div class="card-body">
             <div class="card_title" style="margin-top: -23px;padding-bottom: 15px;">
                 <h4> {{ article.title }}</h4></div>
              <p><a href="{{ article.wiki_page.get_absolute_url }}"> {{ article.wiki_page.title }} </a> &gt;
                  <a href="{{ article.page_category.get_absolute_url }}"> {{  article.page_category.title }} </a> </p>
              <div class="row">

                <div class="author_article">
                  {{ article.is_author.username }}
                </div>
              <div class="created">
                {{ article.time_stamp|date:"Y-m-d" }}
              </div>
                </div>
            </div>
        </div>
    </div>
</div>
      {% endfor %}
         {% else %}
        <div class="card">
          <p>There are no Article yet.  </p>
        </div>
           {% endif %}
    </div>
{% endblock %}