WikisCommunity/home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('', views.index),
    path('policy/', views.policy, name='policy'),
    path('login/', auth_views.LoginView.as_view(template_name='pages/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('register/', views.register, name='register'),
    path('account/', views.edit, name='account'),
    path('page_request/', views.page_request, name='page_request'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
                    template_name='account/password_change_form.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
                    template_name='account/password_change_done.html'), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
                    template_name='account/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
                    template_name='account/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                    template_name='account/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
                    template_name='account/password_reset_complete.html'), name='password_reset_complete'),
]

WikisCommunity/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    path('page/', include('wikipage.urls', namespace='wikipage')),
    path('article/', include('wikiarticle.urls', namespace='wikiarticle')),

    path('', include('home.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WikisCommunity/wikipage/urls.py
from django.urls import path
from . import views


app_name = 'wikipage'


urlpatterns = [
    path('', views.page_list, name='page_list'),
    path('search/', views.page_search, name='page_search'),
    path('<slug:wiki_category_slug>/', views.page_list, name='page_list_by_category'),
    path('<int:id>/<slug:page_slug>/', views.page_index, name='page_index'),
    path('<int:id>/<slug:page_slug>/<slug:page_category_slug>', views.page_index, name='article_list'),

    path('<slug:page_slug>/edit/', views.page_edit, name='page_edit'),
    path('<slug:page_slug>/add_category/', views.page_add_category, name='page_add_category')
]

WikisCommunity/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import DateTimeField
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
"""class AnonyUser(models.Model):
	AnonyUser = models.OneToOneField(User, on_delete=models.CASCADE, blank = True, null = True)
	ip_adresss = models.GenericIPAddressField(null=True)"""


class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	date_of_birth = models.DateField(blank=True, null=True)
	#city = models.CharField(max_length=100, blank=True)
	#country = models.CharField(max_length=100, blank=True)
	photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
	signup_confirmation = models.BooleanField(default=False)

	def __str__(self):
		return self.user.username

	def get_author(self):
		return self.user.username


class PageRequest(models.Model):
	user = models.ForeignKey(User, related_name='user_request',on_delete=models.CASCADE, null=True)
	title = models.CharField(max_length=64)
	content = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	active = models.BooleanField(default=True)

	class Meta:
		ordering = ['-created']

	def __str__(self):
		return '{}: {}'.format(self.user.username, self.title)


"""class IPBlock(models.Model):
	ip = models.CharField(max_length=20)
	block = models.BooleanField(default=False)
	expiration = models.DateTimeField(auto_now=True)

	class Meta:
		permissions = [
			("block_ip", "Can block and remove-block a specific adress IP"),
		]


class UploadProperty(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	#path = models.ImageField(upload_to='users/.../, blank=True')"""

WikisCommunity/home/forms.py
from django.core.exceptions import ObjectDoesNotExist
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, PageRequest
import re #regular expression


class LoginForm(forms.Form):
    username = forms.CharField(label='Username or Email', max_length=30)
    password = forms.CharField(label='Password', widget=forms.PasswordInput())
    

class RegisterForm(UserCreationForm):
    def clean_email(self):
            email = self.cleaned_data['email']
            if User.objects.filter(email=email).exists():
                raise forms.ValidationError('Email already exists!')

            return email

    class Meta:
        model = User
        fields = ['username', "email", "password1", "password2"]


class UserEditForm(forms.ModelForm):
    first_name = forms.CharField()
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    date_of_birth = forms.DateTimeField(label='Date of Birth(yyyy/mm/dd)',
                            required=False, 
                            widget=forms.TextInput(
                                attrs={'placeholder': 'ex: 2012-12-22'}))

    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

class PageRequestForm(forms.ModelForm):
    class Meta:
        model = PageRequest
        fields = ['title', 'content']

WikisCommunity/home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import Profile, PageRequest
from .forms import LoginForm, RegisterForm, UserEditForm, ProfileEditForm, PageRequestForm


def index(request, category_slug=None): 
	return render(request, 'pages/home.html')


def policy(request):
	return render(request, 'pages/pagepolicy.html')


def login(request):
	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			user = authenticate(request, username=cd['username'],
										password=cd['password'])
			if user is not None:
				if user.is_active:
					login(request, user)
					return HttpResponse('Login success.')
				else:
					return HttpResponse('Account is banned.')
			else:
				return HttpResponse('Invalid input.')
	else:
		form = LoginForm()
	return render(request, 'pages/login.html', {'form': form})


def register(request):
	if request.method == 'POST':
		form = RegisterForm(request.POST)
		if form.is_valid():
			new_user = form.save()
			Profile.objects.create(user=new_user)
			return render(request, 'account/register_done.html', 
										{'new_user': new_user})
	else:
		form = RegisterForm()
	return render(request, 'pages/register.html', {'form': form})


@login_required
def account(request):
	return render(request, 'pages/account.html', {'section': 'account'})


@login_required
def edit(request):
	if request.method == 'POST':
		user_form = UserEditForm(instance=request.user, data=request.POST)
		profile_form = ProfileEditForm(instance=request.user.profile, 
								data=request.POST, files=request.FILES)

		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()
			messages.success(request, 'Update success.')
		else:
			messages.error(request, 'Invalid input.')
	else:
		user_form = UserEditForm(instance=request.user)
		profile_form = ProfileEditForm(instance=request.user.profile)

	return render(request, 'pages/account.html', {'user_form': user_form, 
											'profile_form': profile_form})


@login_required
def page_request(request):
	requests = PageRequest.objects.filter(active=True)
	if request.method == 'POST':
		request_form = PageRequestForm(data=request.POST)
		if request_form.is_valid():
			new_request = request_form.save(commit=False)
			new_request.user = request.user
			new_request.save()
	else:
		request_form = PageRequestForm()
	return render(request, 'pages/page_request.html', {'requests': requests,  
												'request_form': request_form})


"""def get_client_ip(request):
	x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
	if x_forwarded_for:
		ip = x_forwarded_for.split(',')[0]
	else:
		ip = request.META.get('REMOTE_ADDR')
	return ip"""

WikisCommunity/home/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
    <meta name="description" content="Cwiki.com">
    <meta name="author" content="LongKhiem">

    <title>{% block title %}{% endblock title %}CWiki</title>
    <link rel="icon" href="{% static 'images/logos/favicon.ico' %}">
    
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/comments.css' %}">
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">
    <link href="{% static 'css/account.css' %}" rel="stylesheet">

    {% block stylesheet %}{% endblock stylesheet %}
</head>

<body>  
    <!-- Navigation bar-->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color:#0D1A26">
        <div class="container-fluid">
            <a class="navbar-brand" href="/" style="color: white">CWiki | Community's Wiki</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">

                    {% block menu %}
                     <li>
      <form class="d-flex justify-content-center h-100"  method="get" action="{% url 'wikipage:page_search' %}">
        <div class="searchbar" style="padding:7px;">
          <input class="search_input" type="text" name="query" placeholder="Page search..." style="height: 27px;">
          <input type="submit" class="search_icon" value="" style="
                 background: url('/static/images/icon_search.png');
                 background-size:cover;
                 margin-bottom: -9px;
                 background-color: aquamarine;
                 width: 25px;
                 height: 28px;
                 margin-left: -5px;
                 "> </div>
      </form>
    </li>
                    {% endblock %}
                    <li class="nav-item"><a class="nav-link" href="/page" style="color: white">Page</a></li>
                     <li class="nav-item"><a class="nav-link" href="/page_request" style="color: white">New Page Request</a></li>
                    <hr style="width: 1px; height: 20px; background: brown; border: none; margin-bottom:-5px;margin-top:10px" />
                    <form class="form-inline">
                      {% if request.user.is_authenticated %}
                        <li class="nav-item dropdown" style="margin-bottom:-6px;">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false" style="color: yellow;margin-bottom:4px">{% if not request.user.is_superuser %}
                                {% if request.user.profile.photo %}
                                  <img src="{{ request.user.profile.photo.url }}" class="circular--square" width="30" height="30">
                                {% endif %}
                            {% endif %}
                            Hello <strong> {{request.user.username}}</a></strong>
                        <!-- Dropdown menu -->
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          {% if request.user.is_superuser %}
                            <li><a class="dropdown-item" href="/admin">AdminPage</a></li>
                          {% else %}
                            <li><a class="dropdown-item" href="/account">Profile</a></li>
                          {% endif %}
                          <li><hr class="dropdown-divider" /></li>
                          <li><a class="dropdown-item" href="{% url 'logout' %}">Log out</a></li>
                        </ul>
                        </li>
                      {% else %}
                        <a class="nav-link" href="/register" style="color: white">Register</a>
                        <br>
                        <a class="nav-link" href="/login" role="button" style="color: white" aria-pressed="true">Login</a>
                      {% endif %}
                    </form>
                </ul>
            </div>
        </div>
    </nav>
    <div>
    <br>
    {% if messages %}
        <br>
        <ul class="messages">
        {% for msg in messages %}
            <div class="alert alert-info alert-dismissable">
                 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{msg.message}}
            </div>
        {% endfor %}
        </ul>
    {% endif %}
    <div>
    {% block content %}
    
    {% endblock %}
    <!-- Footer -->
    <footer>
    </footer>
    
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        {% block scripts %} {% endblock %}
</body>
</html>

WikisCommunity/home/templates/pagination.html
<div class="pagination">
	<span class="step-links">
		{% if page.has_previous %}
			<a href="?page={{ page.previous_page_number }}">Previous</a>
		{% endif %}
		<span class="current">
			Page {{ page.number }} of {{ page.paginator.num_pages }}.
		</span>
		{% if page.has_next %}
			<a href="?page={{ page.next_page_number }}">Next</a>
		{% endif %}
	</span>
</div>